### ISSUE TITLE
Subtitles don't show up

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/codecast#132]
Hi Sébastien, 

The teaching assistant reviewed the srt files of the codecast, it seems that for some of them this is creating issues. The only special character in this subtitle is $. Might this be the problem?

Thanks for your help.
https://codecast.france-ioi.org/v6/editor?stepperControls=_undo,_redo,_expr,_out,_over&base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fdartmouth%2F1517948554914

**Comment by epixode** [comment]
The problem is caused by the blank line at the top of the file between the first sequence number (1) and the first timestam range.  It should be:
```
1
00:00:00,000 --> 00:00:00,760

```

Remove this blank line and it will work.
Marking as enhancement, we can probably find a subtitle parser that is more tolerant, and has better error reporting.

**Comment by EllaHa** [comment]
Thanks Sébastien!
