### ISSUE TITLE
memory visualization incorrect when passing arrays to functions 

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#92]
When passing an array to a function and receiving it as int ptr[] (rather than int * ptr), the memory visualization fails to show any variables from this point onward. Example:

This does not show ptr, size or i in the memory representation:

#include <stdio.h>
void printArray(int *, int);
int main(void) {
    //! showMemory(start=65520)
    int array[] = {6, 2, -4, 8, 5, 1};
    int N = 6;
    printArray(array, 6);
    return 0;
}

void printArray(int ptr[], int size) {
    int i;
    for (i=0; i<size; i++) {
        // printf("%d ", *(ptr+i));
        printf("%d ", ptr[i]);
    }
    printf("\n");
}

This on the other hand works:
#include <stdio.h>
void printArray(int *, int);
int main(void) {
    //! showMemory(start=65520)
    int array[] = {6, 2, -4, 8, 5, 1};
    int N = 6;
    printArray(array, 6);
    return 0;
}

void printArray(int * ptr, int size) {
    int i;
    for (i=0; i<size; i++) {
        // printf("%d ", *(ptr+i));
        printf("%d ", ptr[i]);
    }
    printf("\n");
}

**Comment by epixode** [comment]
Thanks for the report.  I have added support for this use case (deployed on /next for now), let me know what you think.

An unknown-size array is now displayed as a pointer value in the stack view (instead of {…}), and not shown in the memory view (as they are immutable aliases for some other memory location, no memory is allocated for them).

**Comment by petraBT** [comment]
Fantastic- thank you! Variables inside the function are now showing up in the memory representation - great!
